### ISSUE TITLE
Local dev site: "Failed to compile"

### ISSUE THREAD

**Issue by lancehilliard** [tidymemphis/tidymemphis#2]
I'm a Gatsby novice, but I've tried to stand up a Windows development environment and consider contributing. It was a very rocky journey getting Node and Gatsby installed in Windows, but I think I've managed that, and now I'm getting this error when I browse to my `gatsby develop` server locally:

Failed to compile: Multiple "root" queries found: "BlogPostBySlug" and "BlogPostBySlug".

![image](https://user-images.githubusercontent.com/278006/77000856-02cf4300-6927-11ea-9bc1-863d1b6b5e3a.png)

The only "BlogPostBySlug" I see is in blog-post.js, and it seems to be defined only once? Not in multiple? But maybe I'm misinterpreting something (again... _novice_).

Anyhoo -- if someone could help me have a working local site, then maybe I could see about helping out, somehow. Thank you!

**Comment by tidymemphis** [comment]
So I've had troubles with Gatsby and the development server when a blog-related thing that doesn't look important gets deleted. I'm guessing this is all because I started the site based on the [Gatsby Starter Blog](https://www.gatsbyjs.org/tutorial/blog-netlify-cms-tutorial/). So if anything got deleted in the last push, that's probably why.

**Comment by tidymemphis** [comment]
also gatsby-node.js is related?

**Comment by tidymemphis** [comment]
I'm pretty sure this has been fixed by the most recent updates, I'm gonna close this.
